---
- name: Update the server
  apt:
    upgrade: safe
    update_cache: yes

- name: Install required system packages
  apt:
    name: '{{ item }}'
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    - unzip
    - libffi-dev

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Install Docker modules for Python
  pip:
    name: '{{ item }}'
  loop:
    - docker
    - docker-compose

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_installation_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Link docker-compose to bin folder
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Adjust Docker logging strategy
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restart the Docker daemon
  service:
    name: docker
    state: restarted

- name: Create /var/docker folder
  file:
    dest: /var/docker
    state: directory
    owner: root
    group: docker
    mode: 0774

- name: Copy health check script
  copy:
    src: healthchecks.py
    dest: /var/docker/healthchecks.py
